[package]
name = "anstool"
version = "0.1.0"
authors = ["Lucas Russo <lerwys@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
